Adding paper on holder binding to advance reading section
WebOfTrustInfo/rwot11-the-hague pull request #9
Opened 2022-07-08 17:21 UTC by awoie

Adding paper on holder binding to advance reading section

2022-07-11 08:29 UTC, elenachachkarova requested changes
Thank you for your submission. I will merge your code when we add the listing.

2022-07-11 10:12 UTC, awoie commented on advance-readings/README.md
>  ## Alphabetical Listing
@elenachachkarova thanks for reviewing my PR. Yes, I'd prefer if you could just modify and then merge. Thanks!

2022-07-11 10:17 UTC, awoie commented on advance-readings/README.md
>  ## Alphabetical Listing
I believe I included a link to the paper in the README.md already.

2022-07-11 16:44 UTC, awoie commented on advance-readings/README.md
>  ## Alphabetical Listing
also link added to the alphabetical listing section

2022-07-11 23:49 UTC, elenachachkarova commented on advance-readings/README.md
>  ## Alphabetical Listing
@awoie Thank you for making the changes. We will send yo an email with the promo code.

2022-07-11 23:49 UTC, merged

2022-07-18 10:19 UTC, awoie commented on advance-readings/README.md
>  ## Alphabetical Listing
@elenachachkarova i haven't received the promo code yet. can you please send it to oliver.terbu@spruceid.com. thanks!